# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

functionalBART_res <- function(x, y, p, n, funcP, intvls, x_test, n_test, nu, lambda, iXinfo, nc, nkeeptrain, binaryOffset, iter, burn, alpha, beta, tau, dart, dart_fp, theta_fp, omega_fp, a_fp, b_fp, rho_fp, aug_fp, dart_int, theta_int, omega_int, a_int, b_int, rho_int, aug_int) {
    .Call(`_FuncBART_functionalBART_res`, x, y, p, n, funcP, intvls, x_test, n_test, nu, lambda, iXinfo, nc, nkeeptrain, binaryOffset, iter, burn, alpha, beta, tau, dart, dart_fp, theta_fp, omega_fp, a_fp, b_fp, rho_fp, aug_fp, dart_int, theta_int, omega_int, a_int, b_int, rho_int, aug_int)
}

functionalBART <- function(x, y, p, n, funcP, intvls, x_test, n_test, iXinfo, nc, nkeeptrain, binaryOffset, iter, burn, alpha, beta, tau, dart, theta, omega, a, b, rho, aug) {
    .Call(`_FuncBART_functionalBART`, x, y, p, n, funcP, intvls, x_test, n_test, iXinfo, nc, nkeeptrain, binaryOffset, iter, burn, alpha, beta, tau, dart, theta, omega, a, b, rho, aug)
}

